Update README.md
The removed snippet does not work as it introduce the following error.

TypeError: messageBuilder.buildMessage is not a function
    at Bot.pushMessage (<repo>/node_modules/line-messaging/lib/bot.js:142:32)